### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by pdehaye** [chezou/tabula-py#109]
# Summary of your issue
Reported [here](https://github.com/tabulapdf/tabula/issues/920)

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.

This FAQ might be helpful. 
https://github.com/chezou/tabula-py#i-faced-parsererror-error-tokenizing-data-c-error-how-can-i-extract-multiple-tables
