### ISSUE TITLE
It would be nice to be able to include a template (json file tabula-template) directly as an option of tabula-py

### ISSUE THREAD

**Issue by pdehaye** [chezou/tabula-py#111]
(This is a reopening of #110, opened by made to fit the issue template. This was originally submitted by @papagala but I have the same need, AFAICT)

**Is your feature request related to a problem? Please describe.**
I have PDFs with many pages, each presenting a table with the same (lined) structure, but filled differently (some boxes are empty, some are filled, the length varies, it depends on the page). The empty cell and varying lengths of entries mess up the table structure detection, enough that each table is understood to have a slightly different structure, and as a result the JSON output has a different structure page-per-page. 

Note that, in my case, I am actually trying to devise a solution that will assist each of my users in analysing their PDF file consisting of many pages, many tables, etc. The actual content is personal data. To fix ideas, think of me pre-programming a little python script to assist in scraping a PDF printout of their bank statement. 

This is my own problem, but maybe @papagala's is different. 

**Describe the solution you'd like**
My problem can already be partially managed in the following way: from the structure extracted from each page (through method described in #102, for instance), I can figure out programmatically, with some basic logic, which unique structure to use across all the pages. The problem is that I don't have a way to then tell `tabula-py` to use this structure to reanalyse the whole document. 

I imagine I could pass on that structure as a tabula template to `read_pdf`, but AFAICT this functionality is not available right now (but is available in tabula java?). 

**Describe alternatives you've considered**
I could:
 1. use tabula on each page; 
 2. output some JSON;
 3. look at the position of the cells (see #102);
 4. try to reconcile these cell positions across the pages into a global template;
 5. go back, page by page, to transform the JSON output to fit the global template.

I assess 4. to be of medium difficulty and 5. to be hard. Much better would be to, instead of 5., re-use tabula based on the global template.

In my particular situation, where I have to prepare this for others to use, this alternative would be messy, error-prone, and very unlikely to be fixed by end-users.

**Comment by chezou** [comment]
Thanks for requesting it. I still don't understand what is your pain point. Could you give me an example PDF and current workaround code for it?

I'm guessing what you currently do is 1) you specify area of tables for every page by hand, 2) extract the area option each page, 3) extract tables with given area options. If it is true, what is "messy" part?

You said tabula-java can use some templates, but I can't find that function. It'd be nice if you point it out.

**Comment by pdehaye** [comment]
I haven't used the template functionality, but in the tabula.app I do seem to have this option:
![templates___tabula](https://user-images.githubusercontent.com/3274335/45910944-ce4ff900-be0d-11e8-907c-17610a19e72b.jpg). I am not entirely sure what it does, I will admit. 

I am thinking what I need goes beyond any option available through `tabula-py` (but could be wrong of course). The closest I see is [this](https://github.com/chezou/tabula-py/blob/4eb004d4fd69bee34cc19a7edb5f4f3d2de1ce22/tabula/wrapper.py#L460), but it is weaker since it uses fixed columns for a given table. That won't work for me since my cells span more than one column sometimes, leading tabula to insert additional columns. 

Sadly I can't give a sample PDF, but I have generated one synthetic example of _one_ page. 
[example tabula - Sheet1.pdf](https://github.com/chezou/tabula-py/files/2407361/example.tabula.-.Sheet1.pdf) . In my actual situation, imagine that for each individual I have a table like this for 400 pages but with varying number of rows, and the AAAA, BBB and CCC of various lengths, and the XXXs moving about amongst the main set of cells. Because the AAA, BBB and CCC have various lengths, tabula inserts additional rows in an inconsistent manner from table to table. 

Also, I get to see the data for one individual, but want to construct an extractor for everyone, i.e. also the individuals for whom I don't get to see the data.

**Comment by papagala** [comment]
Dear Chezou,

First of all, what a great contribution you are making so thank you so much.

Sorry I was not very explicit earlier, this is what I am proposing. In the Tabula app, as @pdehaye mentions, there is a template option. In my use case I have hundreds of PDFs with the table in the exact same position. So I opened the app and created a template (which is a JSON file with the coordinates of each table) like this:

[
{
"page":1,
"extraction_method":"guess",
"x1":79.9425,
"x2":472.3875,
"y1":479.27250000000004,
"y2":580.2525,
"width":392.445,
"height":100.98
},
{
"page":1,
"extraction_method":"guess",
"x1":57.7575,
"x2":574.1325,
"y1":48.5775,
"y2":299.4975,
"width":516.375,
"height":250.92000000000002
},
{
"page":1,
"extraction_method":"guess",
"x1":57.7575,
"x2":562.6575,
"y1":333.9225,
"y2":424.9575,
"width":504.90000000000003,
"height":91.035
}
]

So given the fact that I already have a JSON file with all the coordinates that I am searching for, I thought there would be an option to input a template into tabula.read_pdf like this:

 df = tabula.read_pdf(filename,template="test.tabula-template.JSON")

Instead I had to first read the "test.tabula-template.JSON"

    with open('test.tabula-template.json', encoding='utf-8') as data_file:
        data = json.loads(data_file.read())
    #Portion of the page to analyze(top,left,bottom,right).
    #y1 = top
    #x1 = left
    #y2 = top + height
    #x2 = left + width    
        
    area = '('+str(data[0]['y1'])+","+str(data[0]['x1'])+","+str(data[0]['y2'])+","+str(data[0]['x2'])+')' 

And then add it like this:

df = tabula.read_pdf(filename,guess=False, area=test, page = 1)

I hope this is more clear. Cheers!

**Comment by chezou** [comment]
@papaga Thanks for clarification, now I understand what you want and I found this issue https://github.com/tabulapdf/tabula/issues/93

Is there specification for template format?

I guess a template file may include one or more settings, how do you want to select one? I think supporting function wchich converts template into tabula-py option is enough rather than passing template file directly. How about this approach?

**Comment by papagala** [comment]
Chezou, 

I belive that approach will work. I am not sure if there is specification, but in my experience is always the same JSON structure since you cannot really pick any options when you are creating a template, the only thing you can do select "N" different areas inside of the pdf (tables), which then translate into a JSON array of N elments. 

Here is another more elaborate JSON template which has the exact same structure as my previous example (hence I think we could use the option approach I was initially proposing)

[
{
"page":1,
"extraction_method":"guess",
"x1":110.5425,
"x2":501.4575,
"y1":328.5675,
"y2":473.15250000000003,
"width":390.915,
"height":144.585
},
{
"page":1,
"extraction_method":"guess",
"x1":110.5425,
"x2":430.3125,
"y1":506.0475,
"y2":583.3125,
"width":319.77,
"height":77.265
},
{
"page":1,
"extraction_method":"guess",
"x1":116.00001000000002,
"x2":425.06001000000003,
"y1":588.6675,
"y2":637.6275,
"width":309.06,
"height":48.96
},
{
"page":1,
"extraction_method":"guess",
"x1":116.00001000000002,
"x2":497.73501000000005,
"y1":648.000135,
"y2":671.715135,
"width":381.735,
"height":23.715
},
{
"page":2,
"extraction_method":"guess",
"x1":159.99974999999998,
"x2":454.52475,
"y1":293.99715,
"y2":388.85715,
"width":294.525,
"height":94.86
},
{
"page":2,
"extraction_method":"guess",
"x1":84.00005999999998,
"x2":529.99506,
"y1":524.00205,
"y2":694.5970500000001,
"width":445.995,
"height":170.595
},
{
"page":3,
"extraction_method":"guess",
"x1":100.00003500000004,
"x2":515.395035,
"y1":262.99935,
"y2":415.99935,
"width":415.395,
"height":153
},
{
"page":3,
"extraction_method":"guess",
"x1":195.99988499999995,
"x2":418.61488499999996,
"y1":524.0020499999998,
"y2":649.4620499999999,
"width":222.615,
"height":125.46000000000001
},
{
"page":4,
"extraction_method":"guess",
"x1":121.99990499999998,
"x2":493.789905,
"y1":193.99635000000012,
"y2":290.3863500000001,
"width":371.79,
"height":96.39
},
{
"page":4,
"extraction_method":"guess",
"x1":144.20250000000001,
"x2":509.8725,
"y1":522.8775,
"y2":673.5825,
"width":365.67,
"height":150.705
},
{
"page":5,
"extraction_method":"guess",
"x1":175.99972500000004,
"x2":438.39472500000005,
"y1":93.00104999999978,
"y2":141.96104999999977,
"width":262.395,
"height":48.96
},
{
"page":5,
"extraction_method":"guess",
"x1":163.32750000000001,
"x2":454.7925,
"y1":301.7925,
"y2":515.9925000000001,
"width":291.46500000000003,
"height":214.20000000000002
},
{
"page":5,
"extraction_method":"guess",
"x1":204.00025500000004,
"x2":409.020255,
"y1":588.9964500000002,
"y2":645.6064500000002,
"width":205.02,
"height":56.61
}
]

Cheers!

**Comment by chezou** [comment]
Ah, a template file generated from single PDF. It'd be helpful if you provide example pair of PDF and template file.

**Comment by papagala** [comment]
Sure, here you go.
[t-table.pdf](https://github.com/chezou/tabula-py/files/2407511/t-table.pdf)
[
{
"page":1,
"extraction_method":"guess",
"x1":51.6375,
"x2":549.6525,
"y1":92.9475,
"y2":559.5975,
"width":498.015,
"height":466.65000000000003
}
]



[table.pdf](https://github.com/chezou/tabula-py/files/2407512/table.pdf)

[
{
"page":1,
"extraction_method":"guess",
"x1":82.2375,
"x2":547.3575,
"y1":141.9075,
"y2":346.1625,
"width":465.12,
"height":204.255
}
]

**Comment by chezou** [comment]
Now start working on #112

**Comment by chezou** [comment]
I implemented `read_pdf_with_template()` function. You can try it on master branch.

Installation:

```
$ pip install git+https://github.com/chezou/tabula-py
```

Example code:

```py
dfs = tabula.read_pdf_with_template('./examples/data.pdf', './examples/data.tabula-template.json', pandas_options={'header': 0})
```

**Comment by papagala** [comment]
I uninstall tabula-py using pip3 uninstall tabula-py. Then I reinstalled it how you mention but I get this.

AttributeError: module 'tabula' has no attribute 'read_pdf_with_template'. Should I raise an issue?

**Comment by papagala** [comment]
alabaster==0.7.10
anaconda-client==1.6.9
anaconda-navigator==1.8.4
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==1.6.1
astropy==2.0.3
attrs==17.4.0
Babel==2.5.3
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.2
bokeh==0.12.13
boto==2.48.0
Bottleneck==1.2.1
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
click==6.7
cloudpickle==0.5.2
clyent==1.2.2
colorama==0.3.9
comtypes==1.1.4
conda==4.4.10
conda-build==3.4.1
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.1.4
cycler==0.10.0
Cython==0.27.3
cytoolz==0.9.0
dask==0.16.1
datashape==0.5.4
decorator==4.2.1
distributed==1.20.2
distro==1.3.0
docutils==0.14
EbookLib==0.16
entrypoints==0.2.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.13
Flask==0.12.2
Flask-Cors==3.0.3
gevent==1.2.2
glob2==0.6
greenlet==0.4.12
h5py==2.7.1
heapdict==1.0.0
html5lib==1.0.1
idna==2.6
imageio==2.2.0
imagesize==0.7.1
ipykernel==4.8.2
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.1
isort==4.2.15
itsdangerous==0.24
jdcal==1.3
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.31.4
jupyterlab-launcher==0.10.2
lazy-object-proxy==1.3.1
llvmlite==0.21.0
locket==0.2.0
lxml==4.1.1
MarkupSafe==1.0
matplotlib==2.1.2
mccabe==0.6.1
menuinst==1.4.11
mistune==0.8.3
mpmath==1.0.0
msgpack-python==0.5.1
multipledispatch==0.4.9
navigator-updater==0.1.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.4.0
numba==0.36.2
numexpr==2.6.4
numpy==1.15.2
numpydoc==0.7.0
odo==0.5.1
olefile==0.45.1
openpyxl==2.4.10
packaging==16.8
pandas==0.22.0
pandocfilters==1.4.2
parso==0.1.1
partd==0.3.8
path.py==10.5
pathlib2==2.3.0
patsy==0.5.0
pep8==1.7.1
pickleshare==0.7.4
Pillow==5.0.0
pkginfo==1.4.1
pluggy==0.6.0
ply==3.10
prompt-toolkit==1.0.15
psutil==5.4.3
py==1.5.2
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.8.2
pyodbc==4.0.22
pyOpenSSL==17.5.0
pyparsing==2.2.0
PyPDF2==1.26.0
PySocks==1.6.7
pytest==3.3.2
python-dateutil==2.6.1
pytz==2017.3
PyWavelets==0.5.2
pywin32==222
pywinpty==0.5
PyYAML==3.12
pyzmq==16.0.3
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
requests==2.18.4
rope==0.10.7
ruamel-yaml==0.15.35
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
Send2Trash==1.4.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.9
Sphinx==1.6.6
sphinxcontrib-websupport==1.0.1
spyder==3.2.6
SQLAlchemy==1.2.1
statsmodels==0.8.0
sympy==1.1.1
tables==3.4.2
tabula-py==1.2.0
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==4.5.3
traitlets==4.3.2
typing==3.6.2
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.1.0
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.2
xlwings==0.11.5
xlwt==1.3.0
zict==0.1.3

**Comment by chezou** [comment]
@papagala I published tabula-py v1.3.0. Could you upgrade to 1.3.0 and try it again?

**Comment by papagala** [comment]
Its working, thank you, you just simplify my code by many lines and processing power which probably saved 1 tree over the course of one year...yes I am overthinking this complement. Thanks anyways!

**Comment by papagala** [comment]
@chezou, I was wondering if it was possible for this method:

 dfs = tabula.read_pdf_with_template('./examples/data.pdf', './examples/data.tabula-template.json', pandas_options={'header': 0})

to accept string as an input ( the actual JSON file or a python list) instead of expecting a file path only or other type of object. This is because I came to the point where I need to dynamically create the template based on the number of pages.

**Comment by chezou** [comment]
I've never tried, but how about using TextIO(json) for second argument?

**Comment by papagala** [comment]
Don't you mean io.StringIO('json')?

**Comment by chezou** [comment]
yes. StringIO(target_dict) might work for it.

**Comment by papagala** [comment]
It did work :+1:  I sometimes believe that developers that are too good come from the future. Thanks a lot
