### ISSUE TITLE
Problem with Tabula 

### ISSUE THREAD

**Issue by mmelnikova1** [chezou/tabula-py#147]
# Summary of your issue

# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: 

```py
# paste output of `tabula.environment_info()`
```

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

Providing PDF would be really helpful to resolve the issue.

- [ ] (Optional, but really helpful) Your PDF URL: ?

# What did you do when you faced the problem?

Provide your information to reproduce the issue.

## Code:

```
paste your core code which reproducible for the issue
```

## Actual behavior:

```
paste your output
```

**Comment by jpricelyftoff** [comment]
**### Environment:**
Paste the output of import tabula; tabula.environment_info() on Python REPL:
CalledProcessError: Command '['java', '-Djava.awt.headless=true', '-jar', '/anaconda3/lib/python3.7/site-packages/tabula/tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--guess', 'CTA3.pdf']' returned non-zero exit status 1.
**###Code:**
from tabula import read_pdf
df = read_pdf("CTA3.pdf")
df
**###Expected behavior:**
would return a df table of bus routes and times.
**###Actual behavior:**
Error: 
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-13-74b551a0ce0e> in <module>
      1 from tabula import read_pdf
----> 2 df = read_pdf("CTA3.pdf")

/anaconda3/lib/python3.7/site-packages/tabula/wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
    106 
    107     try:
--> 108         output = subprocess.check_output(args)
    109 
    110     except FileNotFoundError as e:

/anaconda3/lib/python3.7/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    393 
    394     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 395                **kwargs).stdout
    396 
    397 

/anaconda3/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    485         if check and retcode:
    486             raise CalledProcessError(retcode, process.args,
--> 487                                      output=stdout, stderr=stderr)
    488     return CompletedProcess(process.args, retcode, stdout, stderr)
    489 

CalledProcessError: Command '['java', '-Djava.awt.headless=true', '-jar', '/anaconda3/lib/python3.7/site-packages/tabula/tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--guess', 'CTA3.pdf']' returned non-zero exit status 1.
<img width="1818" alt="Screen Shot 2019-05-21 at 5 19 18 PM" src="https://user-images.githubusercontent.com/48960248/58138765-95f6f980-7bec-11e9-84b4-fc679cc0392b.png">

**Comment by jpricelyftoff** [comment]
I am a beginner so please pardon any simple misunderstandings of error messages. Resources would be useful.

**Comment by chezou** [comment]
Nothing was written in the original issue. I'll close this issue.

@jpricelyftoff Can you create another issue? I'd love you to fill all the questionaries as possible.
