### ISSUE TITLE
Error: returned non-zero exit status 2

### ISSUE THREAD

**Issue by flpvvvv** [chezou/tabula-py#165]
Hi, I had similar issue like other guys when running `read_pdf(example_file)`. I got an error message: 

> returned non-zero exit status 2

I tried many different ways to solve it. Finally I found it. So I would like to share with you.

I solved it my executing: `read_pdf(example_file,shell=True)`
However, I had to modify your python file: **wrapper.py**: change `output = subprocess.check_output(args)` to `output = subprocess.check_output(args,**kwargs)` at line 107. So the argument can pass through to the function `subprocess.check_output`.

I hope it can help others :)

**Comment by chezou** [comment]
Not sure what the root cause is, but according to [this article](http://tldp.org/LDP/abs/html/exitcodes.html), exit status 2 is:

> Misuse of shell builtins (according to Bash documentation)
> Missing keyword or command, or permission problem

So, I can't say anything without your specific script but seems strange to request adding `shell=True`. Anyway, this issue doesn't comply with the issue template so I'll close.
