### ISSUE TITLE
Exception: RuntimeError: java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by Gunnar-Stunnar** [chezou/tabula-py#364]
We are currently experience this exception in our production environment, 
```
Exception: RuntimeError: java.lang.UnsatisfiedLinkError: Native Library /usr/local/lib/python3.9/site-packages/_jpype.cpython-39-x86_64-linux-gnu.so already loaded in another classloader
``` 
This is just the one of a couple that we have seen involving challenge with the java component. We are installing java with 
```
apt-get install -y --no-install-recommends openjdk-11-jre
```
We are running all of this in a linux docker container that is used in Azure cloud functions.

# Check list before submit

- [X ] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [ ] (Optional, but really helpful) Your PDF URL: ?

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [X] Paste the output of `python --version` command on your terminal: ?
- python3.9
- [X] Paste the output of `java -version` command on your terminal: ?
- openjdk-11-jre
- [X] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [X] Write your OS and it's version: ?
-  Docker container: mcr.microsoft.com/azure-functions/python:4-python3.9-appservice

# What did you do when you faced the problem?

We are having to restart our server every-time this appears 

## Code:

```
from tabula.io import read_pdf
...
tabula.read_pdf(path, pages="1", stream=True, area=[...], columns=..., encoding="cp1252")
```

## Expected behavior:

To not throw exception

## Actual behavior:

Throw exception randomly and un-predictable

**Comment by chezou** [comment]
I can't reproduce the issue since I don't have any Azure account. And it looks like the code you've provided isn't enough to reproduce the issue. 
Also, It's hard to guess the environment since the information in the issue template is manually written, while they suggested to copy and paste command output.

I just googled and found that fork may break jpype, instead, we need to use spawn. https://github.com/jpype-project/jpype/issues/1024#issuecomment-1132075890

I'd say you can try a workaround to set `force_subproecss=True` to `read_pdf` function. See also: https://tabula-py.readthedocs.io/en/latest/tabula.html#tabula.io.read_pdf

**Comment by Gunnar-Stunnar** [comment]
Thank you for your timely response, we will try forcing subprocess. If we come along any method to recreating the problems or an explanation to the error we will share it.
