### ISSUE TITLE
jtypes incompatible / not available?

### ISSUE THREAD

**Issue by dpawson** [chezou/tabula-py#399]
### Summary

jtypes requirement not met

### Did you read the FAQ?

- [X] I have read the FAQ

### Did you search GitHub issues?

- [X] I have searched the issues

### Did you search GitHub Discussions?

- [X] I have searched the discussions

### About your environment

```markdown
>>> import tabula; tabula.environment_info()
Python version:
    3.12.5 (main, Aug  7 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]
Java version:
    openjdk version "1.8.0_372-372"
OpenJDK Runtime Environment (build 1.8.0_372-372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)
tabula-py version: 2.9.3
platform: Linux-6.10.6-200.fc40.x86_64-x86_64-with-glibc2.39
uname:
    uname_result(system='Linux', node='fedora-main', release='6.10.6-200.fc40.x86_64', version='#1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024', machine='x86_64')
linux_distribution: ('Fedora Linux', '40', '')
mac_ver: ('', ('', '', ''), '')
```

### What did you do when you faced the problem?

Tried to install jtypes.jtype

 >  python -m pip install --upgrade jtypes.jtype
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement jtypes.jtype (from versions: none)
ERROR: No matching distribution found for jtypes.jtype

### Code

import tabula
tabula.convert_into("Friday Morning Pairs 24-25.pdf", "friars.xlsx", pages="all", format="xlsx")

### Expected behavior

File converted to xsl?

### Actual behavior

>  python pdf2excel.py 
Failed to import jpype dependencies. Fallback to subprocess.
No module named 'jpype'

**Comment by chezou** [comment]
tabula-py optionally depends on `jpype1`, not `jtype`. You can optionally install with jpype by using `pip install tabula-py[jpype]`.

If you don't install jpype, that's not the problem. tabula-py can extract the table with subprocess.

tabul-py provides `output_format` option, which can be `csv`, `json`, and `tsv`. `format` parameter is to pass into tabula-java directly, so you don't need to specify it. I don't know what happens when we pass `xlsx` to tabula-java, but presumably it fails.

If you want to export into xlsx, you should get dataframe first and then convert via pandas' `Dataframe.to_excel()`.

Anyway, it looks like it isn't a bug. I'm closing it. But feel free to reopen if you find any other sign of a bug.
