### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by ufo911** [chezou/tabula-py#88]
I can not use the tool for utf-8 encoding, it writes warning and prints only "?"-s

**Comment by ufo911** [comment]
https://github.com/JonathanLink/PDFLayoutTextStripper/issues/14
has same issue and they fixed It in next PDFbox version and can you also fix ?

**Comment by ufo911** [comment]
Apr 30, 2018 9:08:18 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFO: OpenType Layout tables used in font ABCDEE+Sylfaen are not implemented in PDFBox and will be ignored

**Comment by chezou** [comment]
Could you please **fill the issue template** and reopen? I can't support all the issues without complying issue template due to the limitation of my time for support. **DO NOT SEND EMAIL DIRECTLY.**

The INFO message you provide is not a problem. It's not tabula-java's bug nor tabula-py's bug. I guess you're using Windows and you didn't set appropriate `encoding` option rather than `utf-8` as default. You also have to ensure the font for the command line to be set correctly. Proper encoding depends on what your OS's language is, and I can't help on that point.

I confirmed tabula-py works fine, which means it extracted without any `?`, with Ubuntu.

**Comment by ufo911** [comment]
Apr 30, 2018 9:08:18 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 
INFO: OpenType Layout tables used in font ABCDEE+Sylfaen are not implemented in PDFBox and will be ignored

this error comes from PDFBox version and I think windows is not the problem
[Doc1.pdf](https://github.com/chezou/tabula-py/files/1963027/Doc1.pdf)

this file is my example to convert from PDF and may you test and see that even console says ???

**Comment by ufo911** [comment]
PDFfilename2 = "C:\\Users\\LenovoPC\\Desktop\\Doc1.pdf"

df = tabula.read_pdf(PDFfilename2,
             output_format='dataframe',
             encoding='Ansi',
             java_options=None,
             pandas_options=None,
             multiple_tables=False)



df.to_csv('df_output.csv', encoding='utf-8')

**Comment by ufo911** [comment]
Sylfaen 
Encoding: Identity-H 
may this is problem with document.

**Comment by ufo911** [comment]
your tool is great it really extracts table but need fix for that encoding as i told above..

**Comment by chezou** [comment]
@ufo911 Could you comply [the issue template](https://github.com/chezou/tabula-py/blob/master/.github/ISSUE_TEMPLATE.md)? I'm regretting to respond without filled issue template. I don't want to continue this kind of avoidable communication.

**Comment by ufo911** [comment]
I can but where to send then ? ?

**Comment by chezou** [comment]
Edit the first comment on this issue or create a new issue, which shows the template automatically.
